# Generated by Django 5.1.7 on 2026-03-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_id_alter_servicecategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stylist',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stylist',
            name='work_days',
            field=models.CharField(blank=True, default='', help_text='Example: Monday, Tuesday, Wednesday', max_length=255),
        ),
    ]
