# Generated by Django 5.1.7 on 2026-03-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_approval_time_booking_deposit_amount_and_more'),
        ('services', '0003_stylist_shift_end_stylist_shift_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='services.stylist')),
            ],
            options={
                'verbose_name_plural': 'Stylist Availabilities',
                'ordering': ['stylist', 'day_of_week', 'start_time'],
            },
        ),
    ]
