# Generated by Django 5.1.1 on 2026-02-10 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Joy World Beauty', max_length=200)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='admin_dashboard/')),
                ('primary_color', models.CharField(default='#a86ba3', max_length=20)),
                ('secondary_color', models.CharField(default='#d6a7c0', max_length=20)),
                ('business_email', models.EmailField(default='admin@joyworldbeauty.com', max_length=254)),
                ('business_phone', models.CharField(default='+44 161 123 4567', max_length=20)),
                ('business_address', models.TextField(default='123 Beauty Street, Manchester')),
                ('working_hours', models.TextField(default='Mon-Sat: 9am-7pm, Sun: 10am-5pm')),
                ('booking_policy', models.TextField(default='Cancellations must be made 24 hours in advance.')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_booking', 'New Booking'), ('booking_update', 'Booking Update'), ('new_customer', 'New Customer'), ('low_stock', 'Low Stock'), ('message', 'Customer Message'), ('system', 'System Alert')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_updated', 'Booking Updated'), ('booking_cancelled', 'Booking Cancelled'), ('customer_registered', 'Customer Registered'), ('service_added', 'Service Added'), ('service_updated', 'Service Updated'), ('product_added', 'Product Added'), ('product_updated', 'Product Updated'), ('payment_received', 'Payment Received'), ('message_received', 'Message Received')], max_length=50)),
                ('description', models.TextField()),
                ('related_id', models.CharField(blank=True, max_length=100)),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recent Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
